# docker-compose.yml

version: '3.9'
services:
  user-db:
    image: mysql:8.3
    container_name: user-db
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-user_db}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-changeme}
      MYSQL_USER: ${MYSQL_USER:-nihil}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-changeme}
    ports:
      - "3307:3306"
    volumes:
      - user-db-data:/var/lib/mysql

  user-service:
    build:
      context: ./user
      dockerfile: Dockerfile
    container_name: user-service
    depends_on:
      - user-db
    environment:
      NODE_ENV: production
      PORT: 3000
      USER_DATABASE_URL: mysql://${MYSQL_USER:-nihil}:${MYSQL_PASSWORD:-changeme}@user-db:3306/${MYSQL_DATABASE:-user_db}
    ports:
      - "3001:3000"
    volumes:
      - ./user:/app
    command: ["npm", "start"]

volumes:
  user-db-data:
