# nihil_backend\docker-compose.yml

services:
  user-service:
    build:
      context: ./user
      dockerfile: Dockerfile
    container_name: user-service
    environment:
      NODE_ENV: production
      PORT: 3000
      USER_DATABASE_URL: mysql://root:root@host.docker.internal:3309/nihil_user_dev?connection_limit=5
      FRONT_API_BASE_URL: http://localhost:5173
    ports:
      - "3001:3000"

  post-service:
    build:
      context: ./post
      dockerfile: Dockerfile
    container_name: post-service
    environment:
      NODE_ENV: production
      PORT: 3000
      POST_DATABASE_URL: mysql://root:root@host.docker.internal:3310/nihil_post_dev?connection_limit=5
      FRONT_API_BASE_URL: http://localhost:5173
    ports:
      - "3002:3000"
